{
  "targetLang": "Scala",
  "sourceExtension": "scala",
  "typePerSource": false,
  "keywords": [
    "abstract",
    "case", 
    "catch", 
    "class",
    "def", 
    "do", 
    "else", 
    "extends",
    "false", 
    "final", 
    "finally", 
    "for",
    "forSome", 
    "if", 
    "implicit", 
    "import",
    "lazy", 
    "match", 
    "new", 
    "null",
    "object", 
    "override", 
    "package", 
    "private",
    "protected", 
    "requires",
    "return", 
    "sealed", 
    "super",
    "this", 
    "throw", 
    "trait", 
    "try",
    "true", 
    "type", 
    "val", 
    "var",
    "while", 
    "with", 
    "yield"
  ],
  "escapeKeywordPattern": "`${name}`",
  "typeMap": {
    "any": "Any",
    "boolean": "Boolean",
    "string": "String",
    "number": "Int"
  }
}